provider "aws" {
  region = "us-east-1"
}

resource "aws_security_group" "standard-ssh-sg" {
  name = "standard-ssh"
  description = "Terraform autogenerated aws security group"

  # SSH
  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # out anywhere
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}


resource "aws_instance" "ansible-host" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
  key_name = "first"
  security_groups = ["${aws_security_group.standard-ssh-sg.name}"]
  
  tags {
    Name = "ansible-host"
  }

  user_data = "${file("ansible-setup.sh")}"
}

resource "aws_instance" "nodes" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
  key_name = "first"
  security_groups = ["${aws_security_group.standard-ssh-sg.name}"]
  
  count =2

  tags {
    Name = "node0${count.index + 1}"
  }
}

output "public_ip" {
  value = "${aws_instance.ansible-host.public_ip}"
}

